### ISSUE TITLE
PR's (Feedback)

### ISSUE THREAD

**Issue by Niborian** [v3DJG6GL/truecharts_archive#15]
This time, I made one PR per app. Is this the format you want me to use? Did I do everything correctly, or is there something I missed? I’d love some feedback! :)

**Comment by v3DJG6GL** [comment]
One PR per application is good for me :)
But there are merge conflicts with your PRs, so I can't merge them:
- You created a new subfolder structure `/truecharts_archive/scale-catalog/stable` where you put the updated applications. This is a different folder structure than my catalogue and I don't think it will work that way. Then at least I suppose all the `location` values have to be adjusted as well... 🤔 
- You forgot to update the version values for the `chart.yaml` files. They should be adjusted as well.

Do you want to push fixed to these PRs or do you want start with new pull requests?

**Comment by Niborian** [comment]
I saw the extra folder a few hours ago I must have ruined everything by trying to work on both my laptop and my desktop😅 I thought I changed the `chart.yaml` files, I'm going to push fixes on the existing ones, tho the NZBGet should be fine?

**Comment by v3DJG6GL** [comment]
haha, no worries :)
Yep, the NZBGet should be fine. I don't use this app but the changes itself seems fine as far as I see - I just merged it :)

**Comment by Niborian** [comment]
you can close issue #5 :), also did some testing for the ollama update seems fine for me.
and lastly I have fixed the folder mistake :) so everything should be fine now

**Comment by Niborian** [comment]
@v3DJG6GL 
after a while is it possible to get write* access (with conditions)

like these: no conflicts, passing status checks, review approvals, or code owner approval
(can also have like a have to wait x amount of time if no one reviews its accepted)

Im just asking because I really wanna help 😊

**Comment by Niborian** [comment]
@v3DJG6GL to answer the question about my script, I can send it to you but its work in progress, and idk how easy its to read for others😅
