### ISSUE TITLE
ollama update is broken

### ISSUE THREAD

**Issue by m-aar-ten** [v3DJG6GL/truecharts_archive#16]
I updated Ollama to the newest version, but none of the models will run.
Downgrading fixes the problem, so for now its not a big issue.
logs:
[ollama_ollama-6cd76fff7c-rrxbx_ollama.log](https://github.com/user-attachments/files/17016258/ollama_ollama-6cd76fff7c-rrxbx_ollama.log)

Edit: the problem seems to be Open-UI, using the models via Page Assist works just fine.

**Comment by v3DJG6GL** [comment]
> Edit: the problem seems to be Open-UI, using the models via Page Assist works just fine.

Can you explain how exactly doesn't work? Could it be an upstream issue?

**Comment by Niborian** [comment]
![image](https://github.com/user-attachments/assets/ac8e0569-f9c9-4d43-a385-009097371643)
Seems to be working fine for me, took a while to test since im running on 1500m cpu 😅 but it worked just fine
