### ISSUE TITLE
[QRY] updates for different TRUENAS releases

### ISSUE THREAD

**Issue by rudi-mueller** [v3DJG6GL/truecharts_archive#18]
Apologies in advance as wasn't sure where to raise this question or how to address it.

I am still running the Cobia release version of Truenas.   Never got to migrate to Dragonfish before truecharts turned everything of.

ATM I can't see any advantage for going to Dragonfish and will defineately not be going to EE when its released.  I like the current functionality so see no reason to move and change and subsequently have to redo everything that I have already got running.

So, the question I have, is there a way to identify which version of charts within this archive are targeted for Cobia and which are for Dragonfish??

I expect that I could do a comparison of the changes in each version and look for where the PVC / storage changes are implemented, but is there anything simpler?

Ideally, I would like to update the application versions for the cobia release and am wondering if it worth the effort to do so.

Thoughts and comments appreciated.

**Comment by v3DJG6GL** [comment]
Hey :)

Don't worry, feel free to ask!
My system is also still running on Cobia, I have never upgraded to Dragonfish. And so far all my applications are running fine. I don't think TrueCharts has already made those changes to the TrueNAS catalog that would have made the applications incompatible with Cobia.
And that is also the state this catalog is in. But backups are still super important in case something goes wrong :)

Translated with DeepL.com (free version)

**Comment by v3DJG6GL** [comment]
Hello :)

Don't worry, feel free to ask!
My system is also still running on Cobia, I have never upgraded to Dragonfish. And so far all my applications are running fine. I don't think TrueCharts has already made those changes to the TrueNAS catalog that would have made the applications incompatible with Cobia.
And that is also the state this catalog is in. But backups are still super important in case something goes wrong :)

**Comment by rudi-mueller** [comment]
thanks heaps for answering my questions.
