### ISSUE TITLE
[Request] Additional Apps to Update 

### ISSUE THREAD

**Issue by wetong** [v3DJG6GL/truecharts_archive#2]
Hi, there, 

Great work here, just to check if you can help to update the app to the latest version: ollama 

Much appreciated it.

**Comment by v3DJG6GL** [comment]
@wetong 
Done:

- **Ollama** has been updated to **v0.3.4**
- 
Beware: I haven't checked the functionality since I don't use it. So always backup your data before updating!

**Comment by wetong** [comment]
Noted & thanks for the kindly help.
