### ISSUE TITLE
[REQUEST ] NZBGet docker update

### ISSUE THREAD

**Issue by mivlives4ever** [v3DJG6GL/truecharts_archive#5]
hey v3DJG6GL,

Can you use this docker update to update NZBGet?

https://github.com/nzbgetcom/nzbget/pkgs/container/nzbget

**Comment by Niborian** [comment]
I have changed the docker image, but I have no clue if it works, so if you could test the app using this:

https://github.com/Niborian/truecharts_archive.git

before I push it to this github :)

**Comment by Niborian** [comment]
![image](https://github.com/user-attachments/assets/4ad0e156-d767-4da2-89fe-0d01b680632f)
seems to be working, but I dont use this so please take a look and send me a msg if it works as it should😅

**Comment by mivlives4ever** [comment]
Yes it does work and appears to update, but I was hoping it would update to v24. 3

**Comment by Niborian** [comment]
@mivlives4ever  sorry, my mistake I had put the newer version in the wrong place and dident think about it😅 fixing it now😅 will take about 5min

**Comment by Niborian** [comment]
I cant get it working with the other repository

**Comment by Niborian** [comment]
@mivlives4ever I think it works now, I can atleast login to the webui and see that its running
![image](https://github.com/user-attachments/assets/acbd3074-6014-4dbd-8496-48e635776f22)

Imma make a pull request for this, but please test it.

**Comment by mivlives4ever** [comment]
Tested and working fine, updated to v24.3 successfully...

Thank you!!

**Comment by Niborian** [comment]
@v3DJG6GL  if you could accept #13 this issue will be fixed 😄
